export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";
export const TODO_FETCHED = "TODO_FETCHED";
export const TODO_CREATED = "TODO_CREATED";
export const TODO_DELETED = "TODO_DELETED";
